from core.utils.text2sequence.en.normalizers.acronym_normalizer import ENAcronymNormalizer
from core.utils.text2sequence.en.normalizers.number_normalizer import ENNumberNormalizer
from core.utils.text2sequence.en.normalizers.whitespace_normalizer import WhiteSpaceNormalizer